//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KysParser.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Kys.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="KysParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IKysParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] KysParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.toplevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToplevel([NotNull] KysParser.ToplevelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.kyl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKyl([NotNull] KysParser.KylContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.kys"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKys([NotNull] KysParser.KysContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] KysParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.funcdefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncdefinition([NotNull] KysParser.FuncdefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] KysParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] KysParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.exitprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitprogram([NotNull] KysParser.ExitprogramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentence([NotNull] KysParser.SentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.control"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControl([NotNull] KysParser.ControlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.ifcontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfcontrol([NotNull] KysParser.IfcontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.elsecontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElsecontrol([NotNull] KysParser.ElsecontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.whilecontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhilecontrol([NotNull] KysParser.WhilecontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.twhilecontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTwhilecontrol([NotNull] KysParser.TwhilecontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.waitcontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaitcontrol([NotNull] KysParser.WaitcontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.twbucle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTwbucle([NotNull] KysParser.TwbucleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.timeoutcontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeoutcontrol([NotNull] KysParser.TimeoutcontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.forcontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForcontrol([NotNull] KysParser.ForcontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.forexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForexpression([NotNull] KysParser.ForexpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.varoperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVaroperation([NotNull] KysParser.VaroperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] KysParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.funccall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunccall([NotNull] KysParser.FunccallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.funcresult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncresult([NotNull] KysParser.FuncresultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] KysParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] KysParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.creation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreation([NotNull] KysParser.CreationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] KysParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.asignation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignation([NotNull] KysParser.AsignationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simpleAssign</c>
	/// labeled alternative in <see cref="KysParser.selfasignation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleAssign([NotNull] KysParser.SimpleAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>potencialAssign</c>
	/// labeled alternative in <see cref="KysParser.selfasignation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPotencialAssign([NotNull] KysParser.PotencialAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplicativeAssign</c>
	/// labeled alternative in <see cref="KysParser.selfasignation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeAssign([NotNull] KysParser.MultiplicativeAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>moduleAssign</c>
	/// labeled alternative in <see cref="KysParser.selfasignation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleAssign([NotNull] KysParser.ModuleAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aditiveAssign</c>
	/// labeled alternative in <see cref="KysParser.selfasignation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAditiveAssign([NotNull] KysParser.AditiveAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>equalityExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExp([NotNull] KysParser.EqualityExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncExp([NotNull] KysParser.FuncExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>potencialExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPotencialExp([NotNull] KysParser.PotencialExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aditiveExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAditiveExp([NotNull] KysParser.AditiveExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>moduleExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleExp([NotNull] KysParser.ModuleExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>eqrelationalExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqrelationalExp([NotNull] KysParser.EqrelationalExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplicativeExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExp([NotNull] KysParser.MultiplicativeExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>uniNotExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUniNotExp([NotNull] KysParser.UniNotExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExp([NotNull] KysParser.ParenthesisExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>relationalExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExp([NotNull] KysParser.RelationalExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logicalExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExp([NotNull] KysParser.LogicalExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valueExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExp([NotNull] KysParser.ValueExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>uniAritExp</c>
	/// labeled alternative in <see cref="KysParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUniAritExp([NotNull] KysParser.UniAritExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KysParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] KysParser.ValueContext context);
}
} // namespace Kys.Parser
